[build-system]
requires = ["setuptools>=77.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tmplot"
dynamic = ["version"]
description = "Visualization of Topic Modeling Results"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
license-files = ["LICENSE"]
authors = [
  { name = "Maksim Terpilovskii", email = "maximtrp@gmail.com" },
]
keywords = [
    "data science",
    "data analytics"
]
classifiers = [
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Text Processing :: General",
]
urls.homepage = "https://github.com/maximtrp/tmplot"
urls.documentation = "https://tmplot.readthedocs.io/"

dependencies = [
    "numpy>=1.23",
    "pandas>=1.5",
    "scikit-learn>=1.4",
    "scipy>=1.9",
    "altair>=5",
    "ipywidgets>=8",
    "IPython>=8",
    "tqdm>=4.64",
]

[project.optional-dependencies]
test = ["pytest", "coverage", "build", "twine"]
models = ["tomotopy>=0.8.0", "gensim", "bitermplus>=1.0"]

[tool.setuptools.dynamic]
version = {attr = "tmplot.__version__"}

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
